/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.rspdefinitions;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;

public class BppCommandId extends BerInteger {

	private static final long serialVersionUID = 1L;

	public BppCommandId() {
	}

	public BppCommandId(byte[] code) {
		super(code);
	}

	public BppCommandId(BigInteger value) {
		super(value);
	}

	public BppCommandId(long value) {
		super(value);
	}

}
