/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.rspdefinitions;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;

public class CancelSessionReason extends BerInteger {

  private static final long serialVersionUID = 1L;

  public CancelSessionReason() {}

  public CancelSessionReason(byte[] code) {
    super(code);
  }

  public CancelSessionReason(BigInteger value) {
    super(value);
  }

  public CancelSessionReason(long value) {
    super(value);
  }
}
