/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.rspdefinitions;

import com.beanit.asn1bean.ber.BerTag;
import com.beanit.asn1bean.ber.ReverseByteArrayOutputStream;
import com.beanit.asn1bean.ber.types.BerType;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;

public class CtxParams1 implements BerType, Serializable {

  private static final long serialVersionUID = 1L;

  private byte[] code = null;
  private CtxParamsForCommonAuthentication ctxParamsForCommonAuthentication = null;

  public CtxParams1() {}

  public CtxParams1(byte[] code) {
    this.code = code;
  }

  public void setCtxParamsForCommonAuthentication(
      CtxParamsForCommonAuthentication ctxParamsForCommonAuthentication) {
    this.ctxParamsForCommonAuthentication = ctxParamsForCommonAuthentication;
  }

  public CtxParamsForCommonAuthentication getCtxParamsForCommonAuthentication() {
    return ctxParamsForCommonAuthentication;
  }

  public byte[] getRaw() {
    return code;
  }

  @Override
  public int encode(OutputStream reverseOS) throws IOException {

    if (code != null) {
      reverseOS.write(code);
      return code.length;
    }

    int codeLength = 0;
    if (ctxParamsForCommonAuthentication != null) {
      codeLength += ctxParamsForCommonAuthentication.encode(reverseOS, false);
      // write tag: CONTEXT_CLASS, CONSTRUCTED, 0
      reverseOS.write(0xA0);
      codeLength += 1;
      return codeLength;
    }

    throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
  }

  @Override
  public int decode(InputStream is) throws IOException {
    return decode(is, null);
  }

  public int decode(InputStream is, BerTag berTag) throws IOException {

    int tlvByteCount = 0;
    boolean tagWasPassed = (berTag != null);

    if (berTag == null) {
      berTag = new BerTag();
      tlvByteCount += berTag.decode(is);
    }

    if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 0)) {
      ctxParamsForCommonAuthentication = new CtxParamsForCommonAuthentication();
      tlvByteCount += ctxParamsForCommonAuthentication.decode(is, false);
      return tlvByteCount;
    }

    if (tagWasPassed) {
      return 0;
    }

    throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
  }

  public void encodeAndSave(int encodingSizeGuess) throws IOException {
    ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
    encode(reverseOS);
    code = reverseOS.getArray();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    appendAsString(sb, 0);
    return sb.toString();
  }

  public void appendAsString(StringBuilder sb, int indentLevel) {

    if (ctxParamsForCommonAuthentication != null) {
      sb.append("ctxParamsForCommonAuthentication: ");
      ctxParamsForCommonAuthentication.appendAsString(sb, indentLevel + 1);
      return;
    }

    sb.append("<none>");
  }
}
