/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.rspdefinitions;

import com.waigel.sgp22.asn1.pkix1explicit88.Time;

public class ExpirationDate extends Time {

	private static final long serialVersionUID = 1L;

	public ExpirationDate() {
	}

	public ExpirationDate(byte[] code) {
		super(code);
	}

}
