/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.rspdefinitions;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;

public class LoadCRLResponseError extends BerInteger {

  private static final long serialVersionUID = 1L;

  public LoadCRLResponseError() {}

  public LoadCRLResponseError(byte[] code) {
    super(code);
  }

  public LoadCRLResponseError(BigInteger value) {
    super(value);
  }

  public LoadCRLResponseError(long value) {
    super(value);
  }
}
