/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.rspdefinitions;

import com.beanit.asn1bean.ber.types.BerOctetString;

public class Octet1 extends BerOctetString {

	private static final long serialVersionUID = 1L;

	public Octet1() {
	}

	public Octet1(byte[] value) {
		super(value);
	}

}
