/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.rspdefinitions;

import com.beanit.asn1bean.ber.types.BerOctetString;

public class OctetTo16 extends BerOctetString {

  private static final long serialVersionUID = 1L;

  public OctetTo16() {}

  public OctetTo16(byte[] value) {
    super(value);
  }
}
