/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.rspdefinitions;

import com.beanit.asn1bean.ber.types.BerObjectIdentifier;

public final class OidValues {
	public static final BerObjectIdentifier idRsp = new BerObjectIdentifier(new int[]{2, 23, 146, 1});
	public static final BerObjectIdentifier idRspCertObjects = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2});
	public static final BerObjectIdentifier idRspExpDate = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 0, 1});
	public static final BerObjectIdentifier idRspPartialCrlNumber = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 0, 3});
	public static final BerObjectIdentifier idRspTotalPartialCrlNumber = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 0, 2});
	public static final BerObjectIdentifier idRspExt = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 0});
	public static final BerObjectIdentifier idRspRole = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 1});
	public static final BerObjectIdentifier idRspRoleCi = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 1, 0});
	public static final BerObjectIdentifier idRspRoleDpAuth = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 1, 4});
	public static final BerObjectIdentifier idRspRoleDpPb = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 1, 5});
	public static final BerObjectIdentifier idRspRoleDpTls = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 1, 3});
	public static final BerObjectIdentifier idRspRoleDsAuth = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 1, 7});
	public static final BerObjectIdentifier idRspRoleDsTls = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 1, 6});
	public static final BerObjectIdentifier idRspRoleEuicc = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 1, 1});
	public static final BerObjectIdentifier idRspRoleEum = new BerObjectIdentifier(new int[]{2, 23, 146, 1, 2, 1, 2});
}
