/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.rspdefinitions;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;

public class ProfileInfoListError extends BerInteger {

  private static final long serialVersionUID = 1L;

  public ProfileInfoListError() {}

  public ProfileInfoListError(byte[] code) {
    super(code);
  }

  public ProfileInfoListError(BigInteger value) {
    super(value);
  }

  public ProfileInfoListError(long value) {
    super(value);
  }
}
