/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.rspdefinitions;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;

public class ProfileState extends BerInteger {

	private static final long serialVersionUID = 1L;

	public ProfileState() {
	}

	public ProfileState(byte[] code) {
		super(code);
	}

	public ProfileState(BigInteger value) {
		super(value);
	}

	public ProfileState(long value) {
		super(value);
	}

}
