/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.rspdefinitions;

import com.beanit.asn1bean.ber.types.BerBitString;

public class RspCapability extends BerBitString {

	private static final long serialVersionUID = 1L;

	public RspCapability() {
	}

	public RspCapability(byte[] code) {
		super(code);
	}

	public RspCapability(byte[] value, int numBits) {
		super(value, numBits);
	}

	public RspCapability(boolean[] value) {
		super(value);
	}

}
