/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.rspdefinitions;

import com.beanit.asn1bean.ber.types.BerOctetString;

public class TransactionId extends BerOctetString {

	private static final long serialVersionUID = 1L;

	public TransactionId() {
	}

	public TransactionId(byte[] value) {
		super(value);
	}

}
