/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1implicit88;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;

public class BaseDistance extends BerInteger {

  private static final long serialVersionUID = 1L;

  public BaseDistance() {}

  public BaseDistance(byte[] code) {
    super(code);
  }

  public BaseDistance(BigInteger value) {
    super(value);
  }

  public BaseDistance(long value) {
    super(value);
  }
}
