/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1implicit88;

import java.math.BigInteger;

public class BaseCRLNumber extends CRLNumber {

	private static final long serialVersionUID = 1L;

	public BaseCRLNumber() {
	}

	public BaseCRLNumber(byte[] code) {
		super(code);
	}

	public BaseCRLNumber(BigInteger value) {
		super(value);
	}

	public BaseCRLNumber(long value) {
		super(value);
	}

}
