/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1implicit88;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;

public class CRLNumber extends BerInteger {

	private static final long serialVersionUID = 1L;

	public CRLNumber() {
	}

	public CRLNumber(byte[] code) {
		super(code);
	}

	public CRLNumber(BigInteger value) {
		super(value);
	}

	public CRLNumber(long value) {
		super(value);
	}

}
