/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1implicit88;

import com.beanit.asn1bean.ber.types.BerEnum;
import java.math.BigInteger;

public class CRLReason extends BerEnum {

	private static final long serialVersionUID = 1L;

	public CRLReason() {
	}

	public CRLReason(byte[] code) {
		super(code);
	}

	public CRLReason(BigInteger value) {
		super(value);
	}

	public CRLReason(long value) {
		super(value);
	}

}
