/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1implicit88;

import com.beanit.asn1bean.ber.types.BerObjectIdentifier;

public class HoldInstructionCode extends BerObjectIdentifier {

	private static final long serialVersionUID = 1L;

	public HoldInstructionCode() {
	}

	public HoldInstructionCode(byte[] code) {
		super(code);
	}

	public HoldInstructionCode(int[] value) {
		super(value);
	}

}
