/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1implicit88;

import com.beanit.asn1bean.ber.types.BerGeneralizedTime;

public class InvalidityDate extends BerGeneralizedTime {

	private static final long serialVersionUID = 1L;

	public InvalidityDate() {
	}

	public InvalidityDate(byte[] value) {
		super(value);
	}

}
