/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1implicit88;

public class IssuerAltName extends GeneralNames {

  private static final long serialVersionUID = 1L;

  public IssuerAltName() {}

  public IssuerAltName(byte[] code) {
    super(code);
  }
}
