/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1implicit88;

import com.beanit.asn1bean.ber.types.BerOctetString;

public class KeyIdentifier extends BerOctetString {

  private static final long serialVersionUID = 1L;

  public KeyIdentifier() {}

  public KeyIdentifier(byte[] value) {
    super(value);
  }
}
