/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1implicit88;

import com.beanit.asn1bean.ber.types.BerObjectIdentifier;

public class KeyPurposeId extends BerObjectIdentifier {

  private static final long serialVersionUID = 1L;

  public KeyPurposeId() {}

  public KeyPurposeId(byte[] code) {
    super(code);
  }

  public KeyPurposeId(int[] value) {
    super(value);
  }
}
