/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1implicit88;

import com.beanit.asn1bean.ber.types.BerBitString;

public class KeyUsage extends BerBitString {

	private static final long serialVersionUID = 1L;

	public KeyUsage() {
	}

	public KeyUsage(byte[] code) {
		super(code);
	}

	public KeyUsage(byte[] value, int numBits) {
		super(value, numBits);
	}

	public KeyUsage(boolean[] value) {
		super(value);
	}

}
