/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1implicit88;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;

public class SkipCerts extends BerInteger {

  private static final long serialVersionUID = 1L;

  public SkipCerts() {}

  public SkipCerts(byte[] code) {
    super(code);
  }

  public SkipCerts(BigInteger value) {
    super(value);
  }

  public SkipCerts(long value) {
    super(value);
  }
}
