/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1implicit88;

public class SubjectAltName extends GeneralNames {

	private static final long serialVersionUID = 1L;

	public SubjectAltName() {
	}

	public SubjectAltName(byte[] code) {
		super(code);
	}

}
