/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;

import com.beanit.asn1bean.ber.types.BerObjectIdentifier;


public class AttributeType extends BerObjectIdentifier {

	private static final long serialVersionUID = 1L;

	public AttributeType() {
	}

	public AttributeType(byte[] code) {
		super(code);
	}

	public AttributeType(int[] value) {
		super(value);
	}

}
