/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;

import com.beanit.asn1bean.ber.types.BerAny;


public class AttributeValue extends BerAny {

	private static final long serialVersionUID = 1L;

	public AttributeValue() {
	}

	public AttributeValue(byte[] value) {
		super(value);
	}

}
