/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;

import com.beanit.asn1bean.ber.types.string.BerPrintableString;

public class CommonName extends BerPrintableString {

  private static final long serialVersionUID = 1L;

  public CommonName() {}

  public CommonName(byte[] value) {
    super(value);
  }
}
