/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;


public class DistinguishedName extends RDNSequence {

	private static final long serialVersionUID = 1L;

	public DistinguishedName() {
	}

	public DistinguishedName(byte[] code) {
		super(code);
	}

}
