/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;

import com.beanit.asn1bean.ber.types.string.BerIA5String;

public class EmailAddress extends BerIA5String {

  private static final long serialVersionUID = 1L;

  public EmailAddress() {}

  public EmailAddress(byte[] value) {
    super(value);
  }
}
