/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;

public class ExtensionORAddressComponents extends PDSParameter {

  private static final long serialVersionUID = 1L;

  public ExtensionORAddressComponents() {}

  public ExtensionORAddressComponents(byte[] code) {
    super(code);
  }
}
