/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;

import com.beanit.asn1bean.ber.types.BerObjectIdentifier;

public final class OidValues {
  public static final BerObjectIdentifier idAd =
      new BerObjectIdentifier(new int[] {1, 3, 6, 1, 5, 5, 7, 48});
  public static final BerObjectIdentifier idAdCaIssuers =
      new BerObjectIdentifier(new int[] {1, 3, 6, 1, 5, 5, 7, 48, 2});
  public static final BerObjectIdentifier idAdCaRepository =
      new BerObjectIdentifier(new int[] {1, 3, 6, 1, 5, 5, 7, 48, 5});
  public static final BerObjectIdentifier idAdOcsp =
      new BerObjectIdentifier(new int[] {1, 3, 6, 1, 5, 5, 7, 48, 1});
  public static final BerObjectIdentifier idAdTimeStamping =
      new BerObjectIdentifier(new int[] {1, 3, 6, 1, 5, 5, 7, 48, 3});
  public static final BerObjectIdentifier idAt = new BerObjectIdentifier(new int[] {2, 5, 4});
  public static final BerObjectIdentifier idKp =
      new BerObjectIdentifier(new int[] {1, 3, 6, 1, 5, 5, 7, 3});
  public static final BerObjectIdentifier idPe =
      new BerObjectIdentifier(new int[] {1, 3, 6, 1, 5, 5, 7, 1});
  public static final BerObjectIdentifier idPkix =
      new BerObjectIdentifier(new int[] {1, 3, 6, 1, 5, 5, 7});
  public static final BerObjectIdentifier idQt =
      new BerObjectIdentifier(new int[] {1, 3, 6, 1, 5, 5, 7, 2});
  public static final BerObjectIdentifier idQtCps =
      new BerObjectIdentifier(new int[] {1, 3, 6, 1, 5, 5, 7, 2, 1});
  public static final BerObjectIdentifier idQtUnotice =
      new BerObjectIdentifier(new int[] {1, 3, 6, 1, 5, 5, 7, 2, 2});
  public static final BerObjectIdentifier pkcs9 =
      new BerObjectIdentifier(new int[] {1, 2, 840, 113549, 1, 9});
}
