/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;

import com.beanit.asn1bean.ber.types.string.BerPrintableString;


public class PDSName extends BerPrintableString {

	private static final long serialVersionUID = 1L;

	public PDSName() {
	}

	public PDSName(byte[] value) {
		super(value);
	}

}
