/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;


public class PosteRestanteAddress extends PDSParameter {

	private static final long serialVersionUID = 1L;

	public PosteRestanteAddress() {
	}

	public PosteRestanteAddress(byte[] code) {
		super(code);
	}

}
