/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;

import com.beanit.asn1bean.ber.types.string.BerTeletexString;

public class TeletexOrganizationName extends BerTeletexString {

  private static final long serialVersionUID = 1L;

  public TeletexOrganizationName() {}

  public TeletexOrganizationName(byte[] value) {
    super(value);
  }
}
