/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;

public class TerminalType extends BerInteger {

  private static final long serialVersionUID = 1L;

  public TerminalType() {}

  public TerminalType(byte[] code) {
    super(code);
  }

  public TerminalType(BigInteger value) {
    super(value);
  }

  public TerminalType(long value) {
    super(value);
  }
}
