/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;

import com.beanit.asn1bean.ber.types.BerBitString;

public class UniqueIdentifier extends BerBitString {

  private static final long serialVersionUID = 1L;

  public UniqueIdentifier() {}

  public UniqueIdentifier(byte[] code) {
    super(code);
  }

  public UniqueIdentifier(byte[] value, int numBits) {
    super(value, numBits);
  }

  public UniqueIdentifier(boolean[] value) {
    super(value);
  }
}
