/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.waigel.sgp22.asn1.pkix1explicit88;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;


public class Version extends BerInteger {

	private static final long serialVersionUID = 1L;

	public Version() {
	}

	public Version(byte[] code) {
		super(code);
	}

	public Version(BigInteger value) {
		super(value);
	}

	public Version(long value) {
		super(value);
	}

}
